### ISSUE TITLE
Diversity, Equity & Inclusion Report Release + Follow-up

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#10]
Outstanding Issues: 

- [x] Data
  - [x] Double checking sponsorship allocation calculations
  - [x] Anonymizing & releasing data
- [x] Outstanding unresolved issues in the Google Doc
- [x] Getting someone external to review and provide feedback? (Do we want to do this?) 
- [x] Laying out text & finalizing PDF 
- [x] Putting online onto GitHub 
- [x] Creating clear contribution instructions
- [x] Strategy & communications for releasing report: email, blog post? 
- [ ] Online Community Call / Community Consultation Follow-Up

**Comment by char-siuu-bao** [comment]
Housing the best practices section, and the checklist section on a wiki: https://github.com/sparcopen/opencon-dei-report/wiki

But can also store the open data sets and PDF version in the repo: https://github.com/sparcopen/opencon-dei-report

Ideally, people can either make changes directly into the wiki if they want to contribute, or if they want to start a discussion about something they can start a new issue for it.

**Comment by char-siuu-bao** [comment]
@nshockey – what is the timeline for releasing this for next week? I'm away from Wednesday–Sunday mid-day so ideally if we could do before that, that would be great! 

Could I also get some feedback on which aspects of the report we want to put on the wiki and make publicly editable?  I'm thinking we only want the first two sections - the checklist, and the practices for designing inclusive events (and leaving out the OpenCon self assessment figures and reflection). We can still include the 3rd part of the report on the repo but as a static PDF.

**Comment by char-siuu-bao** [comment]
@txtbks – I've followed up about some data questions in an email!  Once those have been clarified I can start anonymizing the data sets to prep to put online.

**Comment by txtbks** [comment]
@lorrainechu3n Update: I'm struggling to do this on airplane wifi, but I've finished 2016, and am still working through 2015. Sending email with what I have. For 2015 my main issue is that the data is unlinked, so it is difficult to verify. More as soon as I'm on the ground!
