### ISSUE TITLE
June Community Call

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#11]
We need to decide on a theme for the June community call - we'll likely use this time to talk about applications, but Nick -- do we want a broader theme for the call more generally?

**Comment by nshockey** [comment]
Adding @npscience! Do we have more projects that we want to feature, as we have in the past couple of calls? Since the application process (and promoting it) will a top priority, we could theme it around expanding the community / reaching new individuals. Thoughts?

**Comment by char-siuu-bao** [comment]
Hey @nshockey! We can definitely do another project call but if we do, I would like to confirm that fairly soon as for the last two calls I had to actively recruit people to talk on the call (which takes some time to accumulate).  Half the call could be on OpenCon projects, the other half could be an opportunity to talk about the application process (maybe some tips on what we're looking for, how to craft a strong application, and aside from applying to attend OpenCon, what the information will be used for?) – also, maybe some general Q&A to clarify any misconceptions or questions about OpenCon – the global conference in general?

**Comment by nshockey** [comment]
Have we featured someone recently who's doing work to raise awareness about OA/OER/OD on campus or build a culture of open research at an institution (e.g. @rchampieux)? Featuring something like that would feed nicely into the conversation around the application process and raising awareness more broadly.

**Comment by char-siuu-bao** [comment]
@nshockey – I can reach out to Robin if we confirm this as the theme! I also at some point wanted to invite Chealsye to elaborate on her blog post and have a conversation around institutional OA policies.  Would be nice to also get a non-American perspective.

**Comment by nshockey** [comment]
Totally! Roshan, Ahmed, and Osman could all speak to this, though it would also be great to get someone else we haven't featured as heavily... I wonder if any of the OpenCon LatAm organizers have local initiatives that might be a good fit cc @emckiernan @guichactis @ivonnnelujano

**Comment by char-siuu-bao** [comment]
@nshockey - OK! Let me reach out to some of our more global community members/alum.  I'm going to suggest having 3-4 speakers talk about their work on campus (maybe talk about what role OpenCon has played in supporting this?) and then we can open the floor up for general questions about OpenCon and the application process for the last 20-30 mins of the call? Can you be available to answer these Qs (since Joe won't be able to attend the call, I think!)

**Comment by char-siuu-bao** [comment]
(It's on June 28, noon!)

**Comment by nshockey** [comment]
Yep, I'll definitely be on!

**Comment by char-siuu-bao** [comment]
perfect!!

**Comment by char-siuu-bao** [comment]
I'll reach out to some of our satellite hosts who have been doing great work at their institutions and see if they're interested in speaking!

**Comment by JosephMcArthur** [comment]
Looks like we have a game plan here, yes? I might be able to jump on the call a bit late, but, no guarantees. @lorrainechu3n / @nshockey, either of you up for MC'ing the call?

**Comment by nshockey** [comment]
Happy to MC. Would be good to have @txtbks on the call as well. Nicole, are you free at noon ET on the 28th?

**Comment by txtbks** [comment]
Yes! Would be great to have the time dedicated to the application process.

**Comment by npscience** [comment]
Jumping in late to party, sorry -- I've not got a good handle on advocacy groups (not my particular focus) but think great idea to place these types of projects in call with application process, as achievable for many.

Would not be best MC since not got much to add, but sounds like it's all sorted between you -- is that right?

**Comment by char-siuu-bao** [comment]
Thanks @npscience! Yes, I think we're OK and have a game plan - Thanks for checking in!

**Comment by char-siuu-bao** [comment]
We have Robin (OHSU), Ricardo (satellite host from Santiago) and Ahmed (OA Nigeria) confirmed! I've sketched out a rough agenda but Nick or Nicole if you have specific agenda items you want to add about OpenCon and the application process, please drop them in here: https://docs.google.com/document/d/1xItdBIlgUyFugqou4y5ouvNiJhvuvi1A3R6hf2I4LB0/edit#heading=h.i222c2tkoctg  – the call will be the day after applications open so hopefully there will be a good turnout!

**Comment by guichactis** [comment]
I'm not related to campus advocacy here in Argentina, but since we have a national law that mandates open access repositories' creation most universities have created policies and started to implement it. There are a few cases which were pioneers and started advocating for open access before the law's approval. I could reach out to them, but I don't think they have any relation to OpenCon. However, it could be a good opportunity to introduce and promote the event. @lorrainechu3n let me know it you're still looking for initiatives for this or upcoming calls.

**Comment by char-siuu-bao** [comment]
@guichactis Thanks for checking in! We have three speakers confirmed already for this call, and between that and applications, I think we'll have a full slate. But we are planning to have a "getting ready for Open Access Week"-themed call in August, and that would be a great time to hear about institutional open access policies and related laws in Argentina!!

**Comment by nshockey** [comment]
Closing this issue as the call as taken place.
