### ISSUE TITLE
OpenCon feat Open Knowledge Maps

### ISSUE THREAD

**Issue by Bubblbu** [sparcopen/opencon#113]
During the OER Congress I had a brief chat with Nicole about an idea that I've had previously. So before forgetting it again, I'll quickly submit this issue to discuss it with everyone.

Basically, I was thinking of creating an interactive visualization of the OpenCon participants based on [Open Knowledge Maps](openknowledgemaps.org) and the information provided in applications. I think that this would be (1) a great way to explore the pool of fellow OpenConners as one could specifically look for topics/keywords and (2) give some insight about the composition of this year's pool.
Personally I would totally love to have a neat visual overview/summary of all OpenConners with their short bios, interests, links to twitter/orcid/homepages.

I can think of a two main use cases:
- For the participants: (pre-event) networking and familiarizing oneself with fellow participants
- For the OC/staff: eventually it could support the future review process (e.g., automated categories but obv there's lots tbd)

Obviously there's a few things to be considered and which can be probably answered by @sparcopen/staff-opencon?

- Privacy:
    - Can we use application data? (if yes, which parts)
    - What kind of information do we display? (e.g. interface shows computed keywords + bio, profiles but no application text)

And I'd also be happy to hear @sparcopen/oc-opencon's thoughts and ideas! Open for discussion :)

**Comment by nshockey** [comment]
Really like this idea! I think it would be useful to display application text, provided we get participants' permission first.

**Comment by Bubblbu** [comment]
I just wanted to ask whether it is realistic to get a dump of the available data. I understand that this is absolutely not among the important things to do, but as an developer & attendee I'd quite curious to see the results.

So if there's a way to get the data, I'd love to give it a shot :)

**Comment by txtbks** [comment]
Sorry I was a month late in sending the data, but glad it worked! 👍

**Comment by JosephMcArthur** [comment]
@Bubblbu so glad to see this become a thing! Do you still need this issue, or can we close it? Probably better as part of the do-a-thon repo.

**Comment by Bubblbu** [comment]
Yes! Should be moved over to the doathon repo :) Will do!
