### ISSUE TITLE
Review accessibility needs in conference registration form. Get in touch with participant if needed

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#121]

**Comment by JosephMcArthur** [comment]
@lorrainechu3n / @txtbks this was on here as a note, I've just turned it into an issue incase it needed tracking more closely. 

Hopefully, we're all set here and if someone can confirm and close that would be great.

**Comment by txtbks** [comment]
I sent a summary our a couple weeks ago (by email), and nothing else has been added since then!

**Comment by JosephMcArthur** [comment]
sent a summary to staff? I don't recall having seen anything. Don't suppose you could ping me any info you have, I want to make sure we've dealt with anything we can at the venue.

**Comment by char-siuu-bao** [comment]
I received a summary from Nicole, i can forward to you @JosephMcArthur

**Comment by JosephMcArthur** [comment]
we've handled all these and asked for things we've missed in every email.
