### ISSUE TITLE
Design Nametags, etc.

### ISSUE THREAD

**Issue by txtbks** [sparcopen/opencon#122]
- [x] Nametags (already done and brought over by @KTsteen27)

- [x] Nametags for people who registered late

- [x] Speaker name signs

**Comment by txtbks** [comment]
@JosephMcArthur Do we know the wifi information yet? Would be helpful to print on nametags.

**Comment by txtbks** [comment]
@JosephMcArthur @lorrainechu3n - is there a plan for the lectern sign, or do you need me to take care of that too? And if so please LMK if you have a specific vision for the design.

Lectern sign dimensions (moved over from the PDF): 
Frontfläche innen: B = 56,2cm; H = 118,7cm
Breite Front komplett: B = 60cm
Höhe Rednerseite: H = 110,5cm
Ablagefläche: B = 56,2cm; T = 35cm
2* inkl. Mikrofonanschluss + 1* ohne Mikrofonanschluss
vorhanden

**Comment by JosephMcArthur** [comment]
@txtbks if you could that would be really helpful. The only specific is that Nick wants MPG & ideally PLOS too, at the bottom.

**Comment by txtbks** [comment]
@JosephMcArthur Do we have print ready files for them? Should we have a SPARC logo too?

**Comment by char-siuu-bao** [comment]
I don't think we've had the sparc logo on the lectern in the past.

If you need an .Eps file let me know!

**Comment by txtbks** [comment]
I have the SPARC .eps, would be great if you have the OpenCon one handy! (And MPG and PLOS too)

**Comment by JosephMcArthur** [comment]
Personally, I think having a SPARC logo is a touch OTT, as then we'd probably need an R2RC logo too and the text to introduce it. But, @nshockey is the best judge. 

Logo's as follows:
* mpg https://www.dropbox.com/s/57v5zjatd9tkflo/MPG.EPS?dl=0
* opencon https://www.dropbox.com/s/h2ir7r96482ii82/OpenCon2017_Logo_Horizontal.eps?dl=0
* plos https://www.dropbox.com/s/1ehjt7sei3r44dm/PLOS_logo_print.eps?dl=0
* sparc https://www.dropbox.com/s/ouk9ybrdqd7vko3/SPARC-Logo-RGB.eps?dl=0

**Comment by txtbks** [comment]
Done!
