### ISSUE TITLE
Print Things

### ISSUE THREAD

**Issue by txtbks** [sparcopen/opencon#123]
- Find print shop
- Print nametags not printed in DC
- Print speaker table tents
- Print podium sign

**Comment by nshockey** [comment]
The plan is to have Stacie make the nametag in the office on Monday and for Shawn to bring them over with her. We'll still need to print everything else in Berlin. Attaching podium info that @JosephMcArthur got from the venue earlier today.
[The Harnack Haus is not responsible for any failures oft he measuremen1.pdf](https://github.com/sparcopen/opencon/files/1439793/The.Harnack.Haus.is.not.responsible.for.any.failures.oft.he.measuremen1.pdf)

**Comment by txtbks** [comment]
@nshockey OK - that may mean an alternate design plan... I told @JosephMcArthur I could do it, but really won't have capacity over the weekend.

**Comment by nshockey** [comment]
@lorrainechu3n @JosephMcArthur do we have capacity to get the name tags ready before mid-day Monday? If possible, I do think it would be helpful to have them printed in the SPARC office and taken care of ahead of arriving in Berlin. If not, I'm sure we can find a way to make it work in Berlin.

**Comment by txtbks** [comment]
It just occurred to me that I'll be on UK time Monday so probably can get this done by midday US time. We'll inevitably need to print more once we get to Berlin, but agree it would be easier to get the bulk done here.

**Comment by char-siuu-bao** [comment]
@nshockey @txtbks — I can do my best to do it on Saturday - if not I'll keep you all posted and sounds like Nicole might have capacity to do on Monday?  Could you please provide me with all the necessary template information, though?  E.g. if you want to print on the avery nametags again, please let me know the exact size and product # !!

**Comment by txtbks** [comment]
@lorrainechu3n There's some cleaning and collating that needs to happen with the data, so I'm thinking it's probably easiest for me to just do it Monday (though of course go ahead if you want to!)  Can email Stacie about the template info.

**Comment by char-siuu-bao** [comment]
No problem, I'll leave it to you!

**Comment by JosephMcArthur** [comment]
Note, this is connected with #77

**Comment by txtbks** [comment]
Closing this since I think everything is captured in #77
