### ISSUE TITLE
Dine-A-Rounds

### ISSUE THREAD

**Issue by KTsteen27** [sparcopen/opencon#124]
- [x] Create list of restaurants near the venue/hotel
- [x] Assign people to lead dinner (travel to restaurant, gathering attendees)
- [ ] Create sign-up lists 
- [x] Make reservations 

Reservations should be made for 8 pm.

**Comment by JosephMcArthur** [comment]
venue suggested food nearby:

* Piaggio – italian restaurant
* Alter Krug – german restaurant
* Luise – international restaurant (students like the atmosphere there)

All of them are at Dahlem-Dorf – 1 U-train station away or appr. 10-15 min walking distance.
Another one would be:

* Eierschale – international / italian restaurant – 2 U-train station away (Podbielskiallee)

**Comment by JosephMcArthur** [comment]
cc @nshockey about trying to get this sorted. Please veto if you'd like it to not be done for any reason.

**Comment by nshockey** [comment]
I think this is a good idea; however, I would suggest that we identify restaurants around the hotel and encourage people to go there. Downtown Berlin will have a much better selection of restaurants than out by the venue.
