### ISSUE TITLE
August Community Call: Preparing for Open Access Week

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#13]
- Focus on theme "Open in Order to"; as well as invite 1-2 guest speakers
- Consider talking about implementing Open Access policies (e.g. invite Chealsye to talk about her experience?)

**Comment by rchampieux** [comment]
@chealsye and @nshockey would it be possible to include a speaker from the Early Career Librarian OA week project?  Not me (I've been talking too much), but one of other team members?

**Comment by chealsye** [comment]
@rchampieux If this is added to the call agenda, I'd most recommend Camille or Ali as the rest of us tend to be talking lots in other capacities on either the community call or Librarian call.

**Comment by char-siuu-bao** [comment]
Hi just looping in on this thread since the call date is approaching. Confirming that there will be someone talking about the Action Kit? 

@chealsye — would it be possible for you to walk through advocating for an institutional OA policy? I think your blog post instructions were super clear and useful, but it would be great if you could share on the call, since this would be a fairly action-oriented OA week goal for most people to strive toward!

I'd also like to see some more global efforts on OA week? @JosephMcArthur @nshockey — do you know of any initiatives happening outside Europe/NA doing interesting things during OA week? I'll do a call-out via email and social media as well.

Lorraine

**Comment by char-siuu-bao** [comment]
started compiling this database with group at FSCI "Global is Local" session - https://docs.google.com/spreadsheets/d/1lD4pvP_feYGWX00ri2DDMbJXx1r-7mGbeK0asoKJ8wU/edit#gid=0

**Comment by JosephMcArthur** [comment]
A little nudge to @chealsye / @rchampieux for speakers on the OA week project & @chealsye on her institutional policy work. 

@nshockey I'm happy to commit to shipping a draft of content onto the super secret site helping people know what to do during OAweek before this call if you can get some a draft of some content. Might be a _great_ place to hear people's reactions / get feedback before putting everything in place. 

@lorrainechu3n Open Access India are normally pretty busy around this time, happy to ping them a note if you've not got folks in mind now.

**Comment by char-siuu-bao** [comment]
@JosephMcArthur - Great! We now have a few speakers lined up and confirmed (including L. Kelly from OATP, Chealsye, and Mike Galang from McMaster working on a "blackout" library campaign, and @npscience), but it would be awesome to have more non-Western regions speak.  If you also speak about your site I think we should cap it at that for Western speakers. Also — It'll be almost 10pm in India during the community call but I'll reach out to the OA India folks to see if they are interested in speaking!

**Comment by chealsye** [comment]
@JosephMcArthur, @lorrainechu3n confirmed me via email. Call on my calendar, will be there!
