### ISSUE TITLE
Office supplies

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#130]
moved from #77 

- [x] a lot of post-its in a variety of colors
- [x] colored stickers (the little circular ones)
- [x] colored sharpies
- [x] envelopes (we have 102 letters to give out, so 100 is probably fine...)
- [x] scissors

**Comment by JosephMcArthur** [comment]
Roughly (as I need to be on a call for a few hours):

Post its: (5 per group* * 5 number of groups per workshop * 7 number of workshops) = ~180
Sharpies (or similar, but maybe cheaper, pen): ~200 (one per person)
Stickers: ~100 (only one workshop requested these cc @npscience )

* assuming one pack is 100.

**Comment by smlemick** [comment]
We may have that many post its on hand because we hardly used any during the past 2 OpenCons.  Can we cut back the number we schlep over?

**Comment by JosephMcArthur** [comment]
- [x] plain paper
- [x] duck tape
- [x] stapler
- [ ] blue tac

@KTsteen27

**Comment by char-siuu-bao** [comment]
*clarifying 180 pads of sticky notes ... not 180 individual sheets of paper

**Comment by txtbks** [comment]
This is a done as it is going to be!
