### ISSUE TITLE
Compile final attendee data

### ISSUE THREAD

**Issue by txtbks** [sparcopen/opencon#132]
- Regional breakdown
- Gender breakdown
- Scholarship allocation by region
- Number of countries represented
- Percentage of first time attendees

Anything else?

**Comment by nshockey** [comment]
Add percentage of participants who are first-time OpenCon attendees

**Comment by txtbks** [comment]
Closing this because it's on my personal to do list.

**Comment by txtbks** [comment]
@lorrainechu3n The data for everything except scholarship allocation is in a new tab in the decisions spreadsheet (Final Data). I'll add a couple more quick summaries that might be interesting, and then dig into the scholarship numbers, which is going to be a slog.
