### ISSUE TITLE
Check in letter

### ISSUE THREAD

**Issue by nshockey** [sparcopen/opencon#133]
I've updated our welcome letter for this year, available here: https://docs.google.com/document/d/1bQBZJ3iEgVp7hIjnsaMrlF6mkPErUHVSOuUYdLiMtJU/edit# 

@sparcopen/staff-opencon, would be good to get a quick review. Then, we will need to:

- [x] Confirm how many of each version we will need
- [ ] Buy envelopes 
- [x] Print out the appropriate number of copies
- [ ] Sign the letters & stuff the envelopes

**Comment by nshockey** [comment]
Updated letter to include a note about breakfast at the hotel.

**Comment by txtbks** [comment]
Letter looks good. Can obviously take care of the numbers, and happy to add to our print batch tomorrow. Will see if we come across envelopes.

**Comment by txtbks** [comment]
Letters are printed.

**Comment by JosephMcArthur** [comment]
Next year, seems like we might not actually need a letter. Emails are fine??

**Comment by JosephMcArthur** [comment]
@txtbks to attached a pdf of the letter.

**Comment by txtbks** [comment]
To clarify, I'm sending everyone an email confirming their hotel reservation tonight, and will attach the welcome letter when I do. Scholarship recipients will be instructed to check in at the welcome table for their metro pass.

**Comment by txtbks** [comment]
Taken care of by #127.
