### ISSUE TITLE
On-Stage Remarks and Opening Slides

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#134]
- [ ] Need demographic breakdown data from @txtbks  in order to create this slide 
- [ ] Slide thanking OC
- [ ] Slide thanking sponsors by group
- [ ] Slide detailing CoC
- [ ] Housekeeping slide

*** still making this list!

**Comment by char-siuu-bao** [comment]
** Need to make desktop background for speaker laptop too

**Comment by txtbks** [comment]
Background already done and put on the computer :)

**Comment by JosephMcArthur** [comment]
These seem to be more or less done, or at least, there is no time for group input now
