### ISSUE TITLE
DEI report update

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#149]
- [ ] scope updates, what's feasible
- [ ] figure out data we need & assign who gets it
- [ ] reflect and debreif on dei at the meeting and identify next steps
- [ ] draft text
- [ ] review text
- [ ] design it 
- [ ] publish & promote

**Comment by char-siuu-bao** [comment]
Do we want to do this (and the community report) before 2018?  Just trying to figure out my timeline and list of things to wrap up!

**Comment by JosephMcArthur** [comment]
Scope:
* update figures from this year
* update learnings
* Share COC enforcement process
* rename to "V2"
* DEI "favourite session" data
* Potential discussion of dei trade-offs

Process:
* start a gdoc with comments
* focus on non-COC issues to start with.

**Comment by txtbks** [comment]
Re: figures, the data for attendees is clean and ready in the decisions sheet. Might want to check that the speaking roles are properly marked (I haven't been maintaining those), but I can confirm that the attendees, OC, and general scholarship recipients are confirmed correct. If you have any trouble deciphering just let me know! Hope to have the full open data for applicants up in the next couple weeks (see #151).

**Comment by char-siuu-bao** [comment]
@nshockey and @JosephMcArthur could you give me a better idea of what you want the data visualizations to look like? Do you want just this year's data, or do you want it to compare against previous years?

**Comment by JosephMcArthur** [comment]
My feeling is that for the self-evaluation it's all about being able to measure how we're doing, so being able to compare is important. No idea what the trade-offs are though in choosing that.

**Comment by char-siuu-bao** [comment]
Just wanted to know so I could figure out how to format it visually.

**Comment by JosephMcArthur** [comment]
This is updated, and awaiting publication after the OAweek announcement \o/
