### ISSUE TITLE
Purchase any office supplies or banners required

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#206]

**Comment by JosephMcArthur** [comment]
This can be what we had last year (in previous issue):

* at least two mac adapters
* adaptors of all kinds
*

**Comment by ShawnDaugherty** [comment]
- [x] banner
- [x] lanyards
- [x] pronoun badges

**Comment by ShawnDaugherty** [comment]
@JosephMcArthur -- all the adaptors I have are in the box, although they are for newer computers. I don't think it is realistic for us to have adaptors for all possible kinds of computers/cellphones/etc.

**Comment by JosephMcArthur** [comment]
- [x] Print speaker table tents, 1/3 buffer as blank
- [x] Print podium sign (just one)

**Comment by JosephMcArthur** [comment]
- [x]  Direction Signs (tbd)
- [ ] COC signs (around 5)
- [x] Design thinking booklets (around 60)
- [x] Find local print / supplies shops, just in case, including ones open on the weekend

**Comment by JosephMcArthur** [comment]
- [x] Table Names (which may be numbers, but still. These are like table tends, so cardy / thick paper best)

**Comment by JosephMcArthur** [comment]
cc @txtbks for another detail orientated eye on the thead and someone who helped handle this last year.

Some table names that may be missed include: Swag Table, Registration (2), Help Desk (2), Staff Table (4), Reserved (4). Alcohol Free (3)

**Comment by JosephMcArthur** [comment]
- [x] increase amount of stickies & chart paper vs last year as we expect smaller groups. 

They're cheap, no reason to skimp if it causes concern.
