### ISSUE TITLE
Plan January OpenCon Community Call 

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#231]
potential ideas: DEI, project updates, ideas for Open Education week or Open Data Day. call is on january 31st, so ideally having theme set for jan. 15th to advertise/promo!  

http://www.opencon2017.org/january_2018_community_call

- [x] plan theme, update site
- [ ] invite folks to RSVP
- [ ] invite speakers 
- [ ] promote on social media
- [ ] send reminder

**Comment by JosephMcArthur** [comment]
Call seemed pretty wonderful 💯 Good start to the year.
