### ISSUE TITLE
Rating site 404

### ISSUE THREAD

**Issue by npscience** [sparcopen/opencon#36]
@txtbks  - I just tried to access the rating site on Chrome and Safari, both returning 404.

**Comment by txtbks** [comment]
@npscience Try re-clicking your login link (the long one I sent you by email) - the most common cause of 404 is getting inadvertently logged out. If that doesn't fix it, let me know!

**Comment by txtbks** [comment]
Also THANK YOU for reporting issues with the site. So far our servers have been rock solid (thanks @jangondol!) but if there is an issue it's definitely better to know.

**Comment by npscience** [comment]
Oh thank you Nicole @txtbks - the individual login link worked so that must have been cause! Cheers :)

**Comment by txtbks** [comment]
Great! Will leave this issue up since a couple others encountered it too.

**Comment by txtbks** [comment]
Closed since this seems the word seems to have gotten out sufficiently!
