### ISSUE TITLE
Figure out how best to livestream / record this year

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#37]
This year, we're going to have even fewer presentations than last year, but they'll be more targeted. 

Note, in 2 days we'll likely only have around 4.5 hours of meaningful content (although there will be more time spend on intros / housekeeping etc). We'd be paying for about 20 hours of time across both days (including set up, set down)

This calls into question if having a crew livestream everything for 2 days is worth it - or how best to use their time.  

Options:
* have them do business-as-usual
* have them film sessions, then spend the rest of their time making highlight videos on the day
* have them film sessions, then spend time interviewing people or producing something else
* ???? open to other options

**Comment by GrahamSteel** [comment]
My $0.02. Livestreaming and filming events are equally important. I would maximize the use of their time and efforts as per options two or three. At ReConEvent  (in Edinburgh which I co-organize) we had the film crew interview about a dozen of the attendees/speakers last year which worked out extremely well. 

Either way, as per previous OpenCon events, meaningful content should be streamed/recorded - to me, it's just a question of effectively maximizing the use of the crew's time.

**Comment by rchampieux** [comment]
@JosephMcArthur do we have any data on the engagement with the live stream from previous years?  Given the evolving format, I don't think business as usual will work.  I like the idea of devoting more time to filming individual or even project profiles.  Additionally, I wonder if there is a way to use this medium to foster more explicit connections with the satellite events.

**Comment by JosephMcArthur** [comment]
livestreamers confirmed. Pretty similar to last year.
