### ISSUE TITLE
Plan OpenCon Live

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#39]

**Comment by JosephMcArthur** [comment]
I've written up some thoughts on OpenCon Live [here](https://docs.google.com/document/d/1WCWlo_i_xFdxA0l_Hhc_Zd-9ouMX3nM-zB-1Th6VxiI/edit?usp=sharing). 

Some of the key questions raised are:
* OpenCon Live was originally a key DEI initiative for us, how do we understand it now? What DEI challenges can it be used to tackle for us? 
* How can we frame this years OpenCon live around the doathon?
* OpenCon 2016 was about creating content, should 2017 be about curating content? Curated content can then be translated, and engage with other audiences.
* OpenCon live is a key scaling mechanism for OpenCon. With that in mind, how should we use it? What do we want done at scale that Live can play a part of?

Any feedback from @sparcopen/staff-opencon and @sparcopen/oc-opencon would be grand!

**Comment by pennybphd** [comment]
I feel like this is another thing where we can learn from Mozilla sprints
and also the Sustainable Software Institute bods.

**Comment by JosephMcArthur** [comment]
For OpenCon Live this year I'd like to see us:
* Update the OpenCon live webpage design - #107
* Push people down two routes:
  * watching our new issue intro webcasts, and the meeting itself - #96
  * engaging with the doathon - #4 
* continue to have a dedicated person at the meeting to voice questions from twitter. We should encourage people to "meet" there, rather than create siloed communities on other platforms. - #105

This is designed as a minimal set of programming that should be better targeted at the audience, and our objectives.

I'd also like us to consider how we can make our "super workshops" involve people virtually (they'll be kinda similar to community calls, I guess). 

As a stretch goal, we should consider a much deeper focus on content curation before/during/after, for example:
* Using live highlights on our Youtube Live channel to make the stream more engaging
* Creating moments from tweets as they happen
* Creating & translating key session notes
- #106

Please feel free to reopen if you've got feedback, comments or anything like that. Otherwise, on to implementation!
