### ISSUE TITLE
Send Survey to Attendees

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#42]
While we also say we want to prepare this in advance, often it seems we're not sure what the right question is until after the meeting. So, what might be best is to prep things like email text, lists, and a basic template before hand then craft the final questions after.

**Comment by nshockey** [comment]
Is there any prep we should be doing for the survey right now, and can we set a time immediately following the conference to make changes and send it out?

**Comment by char-siuu-bao** [comment]
I have a google doc set up to draft it! On my to do list. I can try to
finish by tomorrow.

**Comment by char-siuu-bao** [comment]
Drafting here if folks want to take a look / give feedback. still very much a draft -
 https://docs.google.com/document/d/1i7MR7ZBPH84bt04R9j5hY6hZ2qiTdfG_pcQ1yckPoxk/edit#

**Comment by txtbks** [comment]
Designed in #142

**Comment by txtbks** [comment]
Here's a draft of the form (please do not try and fill it out yet!) https://docs.google.com/forms/d/1pZnHgX8wpFonuzxMbXV_VhsB-imwFIntmKP3Y7KpGKg/edit

**Comment by JosephMcArthur** [comment]
done!
