### ISSUE TITLE
Day Two Checklist

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#50]
This issue is for noting small things that we need to remember for the day (e.g make sure to bring X, or do Y).

**Comment by JosephMcArthur** [comment]
- [x] @slobo665 to walk round all workshops after each session & photograph all outputs. Then, we'll get them uploaded. 
- [ ] nightly email
- [x] print workshop plans for hosts

**Comment by slobo665** [comment]
Yap
