### ISSUE TITLE
Complete general housekeeping slides

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#53]
- [ ] Set up rolling slides with sponsors, wifi, sched, github for breaks
- [ ] make Q/A slides  
- [ ] test on speaker PC
- [ ] start of day slides (saying when we'll start so we can do stream early)

Put them here: https://www.dropbox.com/sh/bhf3twkz8oocabe/AAA5J1z4E74xZTWQugYWur9Va?dl=0

Find last years here: https://www.dropbox.com/sh/iyg84scqzut3k8z/AAAUi3vfLDlpLOpCF33R3jVja?dl=0

**Comment by nshockey** [comment]
A few thoughts here:

- Make sure SPARC Europe is listed on the sponsor slides as an Organizing Partner
- Create slides with demographic information on this year's participant pool and possibly program speakers as well
- Should we include a slide with a short link to the Code of Conduct and instructions for getting in touch with organizers?

**Comment by char-siuu-bao** [comment]
Yep I'm starting to put this together! 

https://github.com/sparcopen/opencon/issues/134

I can do the rolling slides too but will need someone to look over them

**Comment by txtbks** [comment]
I'm compiling the data for the participant slides in #132. Will have them by Friday afternoon!
