### ISSUE TITLE
Decide the Speaker PC

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#54]

**Comment by JosephMcArthur** [comment]
My notes suggest that last year (mid event at some point) we thought having two speakers laptops (to even more smoothly switch out / test slides would be helpful). Pretty sure this is @txtbks idea.

**Comment by txtbks** [comment]
I'll plan on bringing my personal laptop (2013 Macbook Air with mini display port), which is what we used last year.

**Comment by txtbks** [comment]
Confirming I brought it. Think we can close this and move over to #55.
