### ISSUE TITLE
Set up & test the speaker PCs (and backups)

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#55]
- [ ] test with webcast folks
- [ ] test with basic slides
- [ ] make sure password is clear / set up
- [ ] get on dropbox (already set up)
- [ ] totally clean the account it's using
- [ ] make sure it has all upgrades needed & new software
- [ ] make sure it has a charger
- [ ] make sure we have any dongles required

**Comment by txtbks** [comment]
Confirming I brought my personal laptop (Macbook Air from 2013-ish), which is the same one we used last year. I didn't bring a dongle or extra charger though. I've set up a clean user on the laptop like last year.
