### ISSUE TITLE
Plan what pre-con activities (usually, webcasts) to do

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#56]

**Comment by JosephMcArthur** [comment]
A suggestion / offer from Danielle / Steph (Mozilla) here that I really like:

> For a pre-event "webinar" we could present on Open Leadership 101 as something that folks could go through before coming to Open Con.  It's a free online hour-long course about working openly.

I'm pretty pro having a session that would help prepare people for making the most out of the doathon and I think this could do just that.

**Comment by JosephMcArthur** [comment]
As is the theme of my week... lets recap previous work here. 

# 2014

We did the following webcasts:
* Open Access 101
* Open Education 101
* Open Data 101

The idea here was to provide content that introduced the issues so we didn't have to do this during the meeting.

Feedback/assessment:
... none in the forms that I could find.

# 2015

We did the following webcasts:
* The state of OA
* The state of OE
* The state of OD

The idea here was to provide content that updated our previous descriptions so we didn't have to do this during the meeting.

Feedback/assessment:

![image](https://user-images.githubusercontent.com/4953703/29213317-9c6bb1d0-7e9a-11e7-8b41-278abd600345.png)


# 2016

We did the following webcasts:
* Intro to OpenCon
* Intro to Advocacy & the OpenCon Advocacy Day
* Diversity, Equity & Inclusion

The idea here was the help better prepare participants for the meeting, and start discussions on key topics. 

Feedback/assessment:

Judging by the response rate to the below about 80% of people watched the webcasts.

![image](https://user-images.githubusercontent.com/4953703/29213346-c2316aae-7e9a-11e7-8441-39d20d780d21.png)

# Summary

In short, our watch rate across years is roughly about the same, but our content is _much_ more relevant and doing a better job at preparing our attendees. \o/

The only thing we know is that we need to bring these webcasts earlier in the year (as with everything else)!

# Where to go now

I presume that this year, our aim for these webcasts (preparing people for the meeting) isn't going to change and neither is our approach of not repeating topics we've covered before. However, this year I feel like it's worth trying to consider a move away from webcasts and towards pre-meeting action to prepare people. Instead of asking people to spend hours watching things we could ask them to:
* take actions to prep for the do-a-thon (e.g propose a project, read what others want to do) 
* take time to consider parts of the program like the culture change workshops
* perhaps join a pre-con call with other participants (in some way, shape or form)
* respond to our emails about what they want out the meeting and how they'll do that
* taking part in open leadership training around some key skills e.g https://github.com/sparcopen/opencon/issues/56#issuecomment-321066141
* watching any content we've previously made if they feel it's needed
* Get used to Sched or Github (maybe)
* Read a piece on how to affect culture change
* Complete a pre-meeting checklist of small actions

etc etc. The above isn't meant to be a complete list of ideas or fully thought through suggestions (and of course some of them are actually watching webcasts...), but more examples of what we could ask people to do. When I think about how it's important for people to prep for the meeting this year, I think these are the ideas that come to mind. 

All that said, I think it's very worth still having an "intro to OpenCon" as a way to frame all pre-conference activities and get key messages across. 

Of course, the challenge here is that people will do all these things last minute and we'll have to figure out how best to follow up with people on these actions.

# Feedback

What would be helpful here is to:
* hear any ideas for things we should be covering before the meeting
* hear any feedback on a potential move away from webcasts as pre-meeting preparation
* hear any major feedback / criticism of previous approaches I've not included that might affect our thinking this year

Tagging @sparcopen/staff-opencon & @sparcopen/oc-opencon

**Comment by char-siuu-bao** [comment]
As I've mentioned before, If we choose to do webcasts this again this year, I think one of our top priorities should be making sure our pre-conference webcasts are more inclusive and move away from an exclusively Western primer to some of these issue areas.  Again, I think that especially for the Intro to Open Education webcast, it's important to move away from the American higher education system and (North) American textbook costs when speaking about this issue area.   From what I remember, the OA and OD intro webcasts were more generalizable, but it might be nice to do more inclusive, updated versions of those as well.

**Comment by npscience** [comment]
Re the idea of getting people to absorb action-related items in preparation, e.g. checking out some of the projects, suggesting their own, doing some open leadership training - is it worth having a few 'open office hours' sessions (across different time zones), in which people can sign up to block out time in order to do the prep with a few alum on hand to answer Qs as needed? I imagine most would like to come prepared but may need help scheduling in the attention, and the social draw of getting to meet a few people before they come for the first time may help.

Re webcasts - is there any harm in just directing people to last year's webcasts on YouTube (I found them helpful), maybe with a specified date and time for a group chat about it after? Something lightweight?

**Comment by char-siuu-bao** [comment]
Hey @npscience! What we've done in past years is direct people to older webcasts (specifically the 101 videos, which act as a crash course — definitely nice to have for those newer to certain issue areas).  As I mentioned above however, my main discomfort of these webcasts, some of the content is quite exclusionary and Western-specific, which is not ideal and does not reflect the folks coming to OpenCon (and the majority of those participating in OpenCon Live).  

@sparcopen/staff-opencon Could we make it a priority to update these webcasts?  Do we have the time to do that?

**Comment by aldirdiri** [comment]
I agree with @lorrainechu3n on the need for an update especially the OE section (I could never use any of these resources in Sudan). We can have the old webcasts as "additional readings" while directing participants to the updated ones primarily. We also need to create materials (could include a webcast) for participants to understand what a Doathon is and prepare them for the day.

@npscience I really love Naomi's ideas of having office hours to answer questions.

**Comment by JosephMcArthur** [comment]
Moving forwards, I'd suggest our path forwards here is to:

at least:
* arrange an introduction to OpenCon webcast similar to last year - #97
* build pre-conference activities into the do-a-thon - #4 
* do early reach-out to attendees before the meeting - #7 
* update our issue introduction webcasts to be more globally inclusive (at least our OER cast, with others to be assessed) - #96

and as stretch goals:

* build a pre-conference checklist - #94
* provide recommended reading on culture change - #95

While I like the idea of office hours, sadly I'm yet to see them actually utilized in any of our programs going back years :'(. 

With that, I'm closing this issue!
