### ISSUE TITLE
Evaluate unconference plans

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#6]

**Comment by JosephMcArthur** [comment]
So, I've just looked through the feedback forms / general data & my notes for the past couple of years. I'm looking at 2015 / 2016 materials as in each year the facilitation was basically the same. 

First, both years the Unconference session is rated incredibly highly. Our basic formula works well here, and while almost everyone has a suggestion for how we could improve it's from a standpoint of "this was great and we want more". 

So, here are some key take aways and things to consider going forwards. 

# Sessions need to be an hour

In 2016, we had lots of comments that sessions are too short to "get into it". Those were 40-minute sessions. These comments don't show in 2015, where sessions are 55 minutes.

Since "not getting into it" means that essentially the whole session is wasted we really need to ensure sessions are long enough. This issue may also be a facilitation/planning problem.  

To address, consider:
* Making sessions an hour long
* More time between sessions
* Giving people an intro format to speed up intros
* Provide more support for facilitation

# People need more time than we usually give to get to sessions

Every year it's been a struggle to get people into rooms and have them pick sessions quickly. We need to provide more time for this.

To address, consider:
* More lead time to choose sessions 
* More time between sessions
* Better directions & helpers

# When placed at the end of the day people are too tired or don't attend

There are a lot of comments that "I didn't attend" or "I'm too tired" or often a mix. Signalling that the unconference is not an optional part of the event continues to be important, as does considering where to place it so people bring their a-game. 

To address, consider:
* Don't put at the end of days
* Joe uses and even sterner face when finding people who're not in a session... 
* Split up unconference sessions so they're more manageable

# People never vote... but it might not matter 

We rarely see a significant (read, useful) number of people voting. This is there to help us pick sessions (if there are too many) or allocate room sizes. However, thus far we've not had an issue with either of these points. 

To address, consider:
* Making voting easier (somehow) and providing dedicated time
* Just having staff chose sessions & guess interest (which is basically what happens anyway!)

# There is little reporting out from sessions

Sadly, despite putting in place docs & sched for enable report-outs people rarely do. It seems often the notes docs are really used to the full extent and it's almost certain that sched isn't being used to get in touch with people after the event. 

To address, consider:
* When giving people a 5 / 10 minute warning suggest they switch to doing a report out / finalising outcomes
* Provide dedicated time for report outs in the program
* Chase facilitators more aggressively post event

# Facilitation can be poor & the help we're providing isn't used. 

People will often comment that some sessions feel unfocused, or individuals dominate the conversation, conveners don't have a clear session plan and that role cards aren't used. 

Most of these points boil down to bad facilitation, people not using the help we provide or lack of time to prepare. 

To address, consider:
* Send facilitators tips when they sign up
* Changing the suggestion form to ask facilitators how they'll run the sessions to get them thinking
* Providing "off the shelf" plans for different session types
* Figuring out how to get people to actually use the role cards or making the role cards more useful.
* Having a trained facilitator in all sessions or providing training for facilitators

# Encouraging non-english or other regional / geographic sessions

One of the unconference sessions I've ever seen / heard most about was the Latin American session. This was held in Spanish. This may be something to consider explicity suggesting / encouraging. My main concern is that this may take a whole specific group of people away from general sessions though - which would be a shame. 

# Moderator Diversity

 I did a little review of who in the group is hosting unconference sessions. This wasn't included in the original stats for the DEI report by I've put the data in the same formats / sheets.

### Gender 2016 

| Gender | total|
|--------------------------------|----|
| Female     | 21 |
| Male       | 20 |
| Non-Binary | 0  |

### Gender 2015

| Gender | total|
|--------------------------------|----|
| Female     | 18 |
| Male       | 16 |

### Region 2016

| Region | total|
|--------------------------------|----|
| Africa                         | 4  |
| Asia                           | 2  |
| Europe                         | 12 |
| Latin America & the Carribbean | 3  |
| North America                  | 18 |
| Oceania                        | 2  |

### Region 2015

| Region | total|
|--------------------------------|----|
| Africa                         | 1  |
| Asia                           | 0  |
| Europe                         | 12 |
| Latin America & the Carribbean | 1  |
| North America                  | 10 |
| Oceania                        | 0  |

### Summary

Our gender balance is okay in both years. Our geographic balance improves in later years (probably owing to DEI focus & work to specifically source sessions from across regions).

- [x] Cc @lorrainechu3n to port these into the DEI report, or not if there was a reason why we didn't include this in v1! 

There are almost certainly other (non-numberical & numerical) aspects of DEI we could look at here. 

To address, consider:
* continuing to focus on ensuring our participant run sessions are balanced (so, specific outreach/support)
* Generally continue to discuss how we can support an inclusive environment
* Consider the point directly above this one!

# Misc

Of course, the above aren't the only issues. However, they are the ones that come out most.

However, all of these points come with a MASSIVE caveat. I've literally never attended an OpenCon unconference session since I'm normally troubleshooting/checking all is okay (and taking a little break...). So, there may be some points that I miss. I'd love any feedback/reaction to the above and other insights from sessions I may miss from @sparcopen/staff-opencon & @sparcopen/oc-opencon 

In terms of planning for 2017 we need to:
- [x] complete this evaluation process & noting any actions we want to take forwards
- [x] open up the unconference submissions
- [x] revising any materials for the event
- [x] organizing & updating the materials for unconference presentation (preferably with a bit less innuendo this time)
- [x] planning session by session on the day activities to help planning
- [x] consider who on staff should play point on the unconference (since we have even more participatory stuff this year it may be better if not me)

**Comment by npscience** [comment]
Caveats:
* I was only at 2016 so can't comment on 2015
* In my mind, unconference sessions are either group discussions to share viewpoints/information, or project kickstart meetings (with actual view to engaging afterwards)

Quick thoughts:
* Longer sessions = good by me. 40 minutes was a rush and felt like we couldn't achieve much.
* Maybe some more time and resources to help hosts prepare for a successful session beforehand. I.e. decide the main aim, then plan to achieve just that in the session. Better to come away with a small achievement than a muddled head. (Of course, can't guarantee folks will do this.)
* For project kickstart meetings, I feel like it would be good to have an hour to kickstart on day one, the  another hour to regroup and reassess on day two too. This gives opportunity for others to come in, for some to back out as needed, etc, and gives it some momentum. E.g kickstart session one = ideation and getting voices in the room; kickstart session two = inital project planning, task assignment, and scheduling first 'community call'/other to ensure momentum.

**Comment by pennybphd** [comment]
I agree with Naomi.

Additionally, for kickstart meetings it should be about group goals and
interests. I've been too many at OpenCon and elsewhere where it's one
Global North white man looking for buy-in and volunteer labour for his
great idea, and not any other substantive input. You can ask for volunteers
in a lightning talk or on Twitter - it's a waste of an unconference session.

**Comment by char-siuu-bao** [comment]
Will revisit this thread for a longer comment, but a quick thought /question I wanted to share before I forget — how will the do-a-thon affect unconferences?  There's a lot of overlap between the two (and I imagine some unconference sessions may transform into do-a-thon teams/projects). Do we draw a link between the two? Is this overlap something that we need to account for?  Especially if some people are already reporting feeling tired and too disengaged to attend the unconference sessions, what happens when the do-a-thon (which is more unstructured again) comes the third day after this?? 

question for everyone but wondering what @JosephMcArthur's thoughts are on this too of course!!

**Comment by JosephMcArthur** [comment]
Thanks for the feedback all. Sounds like what I'm suggesting isn't too far off.

I think there are two key improvements to make this year:
* Provide better support for facilitators - #98
* Encourage reporting out, and feeding into the doathon - #99

and there are a bunch of suggestions for those above. 

I'd also suggest we dogfood the planning process by using our own guide during the planning process. 

With that, I'm closing this issue. Please reopen if you have further ideas, comments, and feedback.
