### ISSUE TITLE
Figure out Speaker Timekeeping & Q/A logistics

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#60]
- [ ] Assign someone to help switch slides between talks
- [ ] Design / Print Speaker logistics
- [ ] Assign someone to help keep us to time
- [x] Figure-out our mic runners
- [ ] Decide how to handle Q&A / communication with moderators
- [x] speaker plaques

**Comment by JosephMcArthur** [comment]
@KTsteen27 please document chats from today

**Comment by txtbks** [comment]
Katie and Brady are all over this.
