### ISSUE TITLE
Design Nametags

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#63]

**Comment by txtbks** [comment]
Note that in the registration form we collect the following information:
- First name (BIG FONT)
- Last name
- Affiliation (people were instructed to separate multiples with " / ")

Things we have and could consider including
- Twitter handle
- Country

Other design thoughts:
- Make nametags double sided, so when they flip around you still see the same info
- Include wifi, URL for sched, and hashtag

**Comment by char-siuu-bao** [comment]
maybe a link to the CoC at the back? or a mini summary of CoC / other quick reference links / emergency contacts for reference. (not on the badge itself but as a little insert we can put in the tag) 

I would not try to fit too much information on the front of the tag itself - it will look crowded.

**Comment by JosephMcArthur** [comment]
@lorrainechu3n any progress here, would be something we should finalize this week I expect.

**Comment by nshockey** [comment]
Just a note that we should have this finalized by Monday, Nov 6, so that Stacie can print and make these in the SPARC office.

**Comment by txtbks** [comment]
They are already in Berlin, thanks to Katie! 
Front: big first name, small last name, small affiliation. 
Back: wifi, sched link, CoC link, hashtag

Will need to do a second run here for the people who registered late, but the bulk are done.
