### ISSUE TITLE
Order any resources needed

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#64]
First, we'll need to sort the logistics for gettings stuff over. So, either
- [x] figure out who can bring things on planes
- [x] see if the venue can store / accept things sent

Then, here is a running list of things we've needed before (probably not complete)

- [x] Nametag holders
- [x] Pronoun tags
- [x] table cards
- [x] Lanyards
- [x] stickers
- [x] stage dressing
- [x] batteries
- [x] spare chargers / converters
- [x] help box (snacks, meds)

**Comment by nshockey** [comment]
I marked a few things as done above. Stacie estimates that we have enough pronoun ribbons for this year. We'll produce the table cards and any other signage needed in Berlin the week before. Same goes for our essential supplies box. We may have enough stickers as well, though I'll have to check. I wouldn't worry about buying extra batteries / chargers / converters in advance. If people need them, we can deal with those problems if they arise.

**Comment by JosephMcArthur** [comment]
got, or don't need, all of this.
