### ISSUE TITLE
Get the OC community sub-group up to speed with community work

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#7]

**Comment by rchampieux** [comment]
Hey @JosephMcArthur! I mentioned on the last OC call that I'd be happy to write a blog post about the benefits of sponsoring a scholarship from an institutional perspective.  Would that fall under this subgroup?  If so, can you give me a deadline....so I'll do it 😀 🐱 🍪

**Comment by JosephMcArthur** [comment]
@rchampieux best to work with @lorrainechu3n / @nshockey on this I think. Let say the end of July as a deadline :)

**Comment by JosephMcArthur** [comment]
@rchampieux best to work with @lorrainechu3n / @nshockey on this I think. Let say the end of July as a deadline... since you asked :)

**Comment by JosephMcArthur** [comment]
Closed by #89 and many other contributions from the OC.
