### ISSUE TITLE
Generate 2018 Logos 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#72]

**Comment by JosephMcArthur** [comment]
@lorrainechu3n when you get a few minutes can you put together some logos for 2018, incase we need them?

**Comment by char-siuu-bao** [comment]
Sorry for being so late on this! They are all here: https://drive.google.com/drive/folders/1sOlxV3x9zg8onmfO0d8_E6gvnwo4oLkL?tid=0B5p6zg4N7rkNbzZWTnl2ck1JQ1E
