### ISSUE TITLE
Draft & release logistics page

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#75]

**Comment by txtbks** [comment]
Just a quick flag that I hid a lot of last year's text in the HTML of the FAQ and attendee FAQ pages. So be sure to check the HTML view in NB before re-writing stuff (obv details will change but may be helpful to see what we covered last year).

**Comment by JosephMcArthur** [comment]
I've now updated the logistics page with basic information for this year. It's ready for feedback on what's on the page. While I was there I've done a big overhall of the page HTML to make it easier to edit & maintain (added styling, removing dead code & documented) so it should be easier to dive in if you want to add/change stuff directly.

Some notes on improvements I'm going to make:
- [x] reuse language for registration forms for accessibility info
- [x] reuse language for Code of Conduct notice from registration form
- [x] Note where people can find room images for the venue

@sparcopen/staff-opencon

**Comment by JosephMcArthur** [comment]
Starting to gather a longer list now:
- [x] Consider reordering the page links to preference higher relevance things
- [x] Decide where to put Nicole's medical / snack box.
- [x] Put in emergency numbers
- [x] Refactor 'sharing' sections to take up less space on header so other parts stand out
- [x] Add in something about our commitment to making everyone at opencon feel safe. Hopefully, encourage sharing of concerns. 
- [ ] use simple language whenever possible

**Comment by char-siuu-bao** [comment]
@JosephMcArthur - thanks so much for putting this together! This looks already WAY more organized than last year's page, I think participants will really appreciate it.

**Comment by JosephMcArthur** [comment]
Okay, done all the above, added a bunch more info, and put the page in the header. 

Outstanding things can't be done until closer to the time (with a reminder at #74 and todo's in the code itself), or I'm awaiting info (which I'll slot in when that comes).

Going to close for now. But reopen if you want me to add more.
