### ISSUE TITLE
Plan Super Workshops

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#78]

**Comment by JosephMcArthur** [comment]
This year we're working on a change to our usual workshop format with our mission "culture change at scale" in mind. 

In previous years we had different workshops on different topic areas - one idea that we are exploring this year, instead of having different workshops exploring different concepts, having ALL workshops structured around ONE idea. e.g. on how to create a culture of Open in your campus or community, and then running 8-12 (or however many) focusing on that topic but in different contexts (e.g. geographically or disciplinary or career stage or background or issue area) 

In this issue what we'd like to do is to identify the high-level milestones/points for how we'll make these happen, and it's a space to refine the idea generally. 

Before we go much further, it's probably worth noting that the name "Super Workshops" should probably be changed ;) 

## Current sketch of the workshops

_I should note, some of this is taken from what our OC / staff has discussed and approved explicitly, and some of it is me filling in gaps based on what we normally do_

* Aims:
  * Feed ideas for action into the do-a-thon and beyond
  * Build connections between people in regions/disciplines
  * Generate shared understanding of day to day and high-level challenges
  * Generate a workshop plan that could be used by others. 
* Hosts: A mix of staff and participants. Who ever is hosting, the plan is to be much more hands on in planning these workshops than normal. 
* Lenght / timing: Two 1-2 hour workshop on day 2. In each slot, we'd focus on either geographic or disciplinary issues. 
* Amount: We might have between 8-12 in each slot, although we're flexible here. We'll need to consider how many we can do with room #'s
* Attendance: We'll probably let people chose their own sessions here... however we'll closely model workshop availability to likely attendee interest.

Also, by "culture change at scale" we usually are talking about contextual culture change towards a more open, diverse, inclusive & equitable academic culture.

I've set up a publically editable document with the above (as this will be easier to edit moving forwards): https://docs.google.com/document/d/1JR65FPCDSXWY3J4HzSInLdjZqP7ksumjqr5s5xxh_C0/edit?usp=sharing. 

Some of the concerns I don't think we've fully addressed so far are:
* OE might not fit as neatly into these discussions as OA / OD
* How many people we have attending who could confidently / productively facilitate discussions of DEI

## How to get there

- [x] Discuss and refine the above foundational points

... the following will probably need to be their own issues. But, would be good to know if I'm missing any major milestones along the way of delivering this before thinking about key actions & timelines. 

- [x] Identify who on staff will take the lead for these workshops
- [ ] Develop an initial workshop plan (including how to feedback workshop discussion to the conference/community at large)
- [x] Identify how many workshops we need and on what topics
- [ ] Identify who should host & invite them
- [ ] Train workshop hosts and adjust the plan based on feedback
- [ ] Ideally... test the workshop somewhere (where can we do this?)

In terms of a broad timeline for these, there are no obvious reasons to not start planning these asap. We certainly don't want to be working on this in the final two weeks when we're dealing with final minute logistics. 

# Feedback

As ever, would be great to hear from @sparcopen/staff-opencon & @sparcopen/oc-opencon (and anyone else reading).

**Comment by aldirdiri** [comment]
There's a lot to be said here especially there are different approaches to each group (students, librarians, researchers ..etc). For example there were many times when I approached students that I had BUILD a culture rather than changing one (which is the case for many African and Middle Eastern countries that I've worked in). So with the vast representation our OC creates and with keeping such differences in mind I believe we can design a list of workshops that would feed into the one theme we have for this year. Do you have a drafted list of workshops for us to suggest and comment? or would you like to create a google doc to brainstorm?

When having the topics ready we can proceed to suggesting and inviting hosts, train them, and develop strategies to capture the outcomes. Workshops can also be designed in a way to feed the Doathon.  @JosephMcArthur

**Comment by JosephMcArthur** [comment]
- [x] @nshockey, can you confirm how many workshop type rooms (and which ones) we've ended up with. My notes suggest we could have as many as 8 rooms that could be used for workshops on Saturday & Sunday, but the sizes vary and that affects how we make groups. 

Provisionally, here are some example room sizes: 128, 68, 42, 22, 24, 24, 12 with a lot of informal space good for smaller groups (~8) dotted around the venue. 

We'd suggested that one session may split by geography. I've provisionally suggested what that might look like based on estimates from 2015 attendee numbers:

 * North American
 * North American 2 (assuming similar numbers to 2015)
 * Latin American
 * EU 1
 * EU 2
 * EU 3 (assuming we'll have more local people. We may be able to make logical splits like east / west. Just got to be careful the UK folks in these groups don't split off and try to form their own "international" group.)
 * Africa
 * Asia & South Pacific

The second group was penciled in as by discipline. This makes sense for OA / OD, but maybe less so for OE. 
- [ ] @nshockey / @txtbks any opinions on what makes sense here? Perhaps we could look at career stage instead, or background (lib, researcher, etc etc)? We could also do a mix, so some groups targetted for OA/OD & others for OE. 

The above gives us group sizes of ~30, which feels reasonable for a participatory workshop (considering facilitators can further divide). However, the venue does lend itself perhaps better to even smaller group sizes as there is a lot of informal & small space. Originally @nshockey we considered 8-12 as group sizes (maybe even more groups). With this comes more training for facilitators, and uncertainty about rooms / space. 
- [x] @nshockey do you want to try for this or stick to the number of rooms we have? 

I'd like to get these few things nailed down this week so that we can make sure that we have a good list of hosts during the #27.

**Comment by JosephMcArthur** [comment]
Got time to chat with @nshockey yesterday, with a few outcomes:
* we need to follow up with the venue about room space
* we want to stick to the number of rooms we have for workshops. 
* we should split north american groups by institution type (R1, and others) 
* within workshop groups, we should try not to further segment group in workshop plans. For example, we shouldn't facilitate small groups by having a researcher group & librarian group. 
* we should add a feedback session from the workshops on the morning of the doathon - #4 

However, there is one point we'd really like @sparcopen/staff-opencon and @sparcopen/oc-opencon input on.

We had planned to use our "super workshop" time (2 hours) to look at culture change through a geographic lens, and then another lens (e.g disipline). However, Nick & I now think it may be best to only focus on geography. We're concerned that two hours isn't long enough to cover two topics well. This could mean:
* pro: 1/2 the work training facilitators & planning workshops
* pro: a greater ability to have outcomes from workshops
* con: isolating participants from the diversity of the meeting
* con: we lose a piece of programming orientated by discipline, which is something we'd like to cover. This could be mitigated by in #90 

We'd be interested to know if anyone has opinions either way on this.

**Comment by JosephMcArthur** [comment]
A small update here: https://docs.google.com/document/d/1JR65FPCDSXWY3J4HzSInLdjZqP7ksumjqr5s5xxh_C0/edit#heading=h.sqn3b3o8xfqs. I have made some example themes & plans for these workshops based off the last discussions with the OC. 

Would invite feedback from @sparcopen/staff-opencon & @sparcopen/oc-opencon. @lorrainechu3n these workshops are based largely around design thinking, and so I'd really value your feedback on that.

**Comment by npscience** [comment]
@JosephMcArthur I really like how the workshops aim to crystallise key issues for work in the doathon the next day. The example workshop plan makes sense to me.

Would it be worth encouraging post-it use in the first half exercises? I’ve found them a good way to capture thoughts concisely, and then you can reorganise: eg group by common theme, eliminate duplicates.

**Comment by JosephMcArthur** [comment]
okay, this is now all being implemented, so closing now!
