### ISSUE TITLE
Coordinate Help Desk

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#79]
A full time help desk clearly provided for the event would be helpful (and we end up doing this ad-hoc each year anyway). 

Here we can make sure that people can always find help with:
* Wifi
* Sched
* Directions / maps
* Code of conduct
* Slide submission / testing

This might also help with people not coming to the staff time in the event which would help with us focusing on whatever is most urgent then & keeping noise down.

We should also think about how to provide this at any event venue.

**Comment by txtbks** [comment]
I wouldn't call it ad-hoc :) but like the idea of more clearly marking and publicizing it. Last year we also provided basic medical and hygiene supplies, extra food, basic office supplies (scissors, markers, pens), and a list of nearby facilities. Would be also super helpful to check if we can have a printer at/near the desk. One thing I wish we'd done last year is better leverage the OC to help staff it during breaks/busy times, so would be great to include this in the signup.

**Comment by JosephMcArthur** [comment]
- [ ] One thing I need to make sure gets done here is on Saturday lunch people will meet here to have lunch. Whoever is on the desk will need to know about this.

**Comment by JosephMcArthur** [comment]
P.s I secured space for this, and have a "help desk" on the agenda.

**Comment by txtbks** [comment]
Ok per our conversation today, Shawn and I will work this out, and we'll make sure to have time during the walkthrough to run down the list of things (above) and make sure we're all on the same page.

**Comment by txtbks** [comment]
Collecting all of the things into one list (add as we think of them)...

Helpdesk can help with:
- Registration
- Wifi
- Using Sched
- Directions / maps
- Code of conduct
- Slide submission / testing
- Printing

Helpdesk offers:
- Basic medical and hygiene supplies
- "Emergency" food
- Basic office supplies (scissors, markers, pens)
- List of nearby facilities (pharmacy, health clinic, hospital)

Need to plan:
- Extra staffing during the mornings, especially first morning
- Staffing during the day

**Comment by JosephMcArthur** [comment]
In morning registration, can we put more staff on the desk & expand it to:

* check if people have signed in on sched yet. That can be seen at a glance here: https://opencon2017.sched.com/editor/users?r=artists . That way we can see if people have their SOS / workshop session successfully assigned. 
* take a temperature check on the do-a-thon. We can define some quick, yes / no questions in #46 (e.g have you been to a hackathon before, have you seen the site & copy, do you have Q's (if yes, put on post-it and put somewhere))

I think this is can help us side-step a few issues this year, and will require just one or two more staff and a bit of planning. Anything we learn here can then be communicated and solved with email & housekeeping time.

**Comment by JosephMcArthur** [comment]
- [ ] joe / shawn / katie / brady to discuss

**Comment by txtbks** [comment]
This will be fine.
