### ISSUE TITLE
Evaluating Successful Projects & Project presentations

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#80]
_I originally sent the below to @nshockey following up on a phone chat we had about the program but realised it can go here too!_

Now we have a draft program in hand I went back and looked at that vs feedback from last year. I noticed that both the things we do to highlight projects don't seem as helpful as other sessions.

<img width="582" alt="screenshot 2017-08-08 21 17 53" src="https://user-images.githubusercontent.com/4953703/29208904-dc8701d2-7e83-11e7-972a-d5211be1c1e0.png">

And so I can't help but try and interrogate why we do these sessions and if we can do something better. The sort of answers I came up with were:
* Motivating for project leads & lends some prestige
* Helps for people to see their peers doing work. After all... we're all about advancing the movement! 
* (when we first started) this was how our participants got on stage
* People may find a project they want to join/mimic
* Surfacing cool projects we don't know about
* Helps people justify attending
* Gives us a way to raise the profile of projects we like
* Gives projects a resource they can use after (their talk as a video)
* They're quite easy to arrange
* We think successful project panels will be inspirational

I'd love to know what others consider the top reasons for those types of programming. It may be worth dropping a note to our previous speakers in these sessions and see how valuable they found it and if it's having the types of outcomes from speakers we'd expect. 

When we've chatted previously about this we've said it's probably worth considering alternative ways of delivering these goals. I've thought about that a bit (and spit balled with @lorrainechu3n too). We thought about:
* [World cafes](http://www.theworldcafe.com/key-concepts-resources/world-cafe-method/)
* Poster sessions
* Story of self style sessions... but for projects
* Having talks about overcoming common challenges, where projects are used as a case study
* [Guacamole workshops](https://uaem2015london.wordpress.com/program/guacamole-workshop/)

While each had some legs, I don't think either of us felt like we'd really cracked it as each session has downsides. That said, I doubt any downside isn't possible to minimize given commitment, time and thought.

After this I started to ask a different question. If this isn't that useful, and there isn't a clear way to think about improvement, then what would be more useful? For this, I went to our data on alumni needs which we've already discussed is fairly consistent across years (and while might not be representative of the community at large is probably fine for the event). 

<img width="578" alt="screenshot 2017-08-09 10 33 50" src="https://user-images.githubusercontent.com/4953703/29208882-cb764c7c-7e83-11e7-8462-209ba66af50e.png">

If you take this at face value, one thing jumps out. Information about projects is one of the lower things on this list of needs (6th). And, out of things we could actually provide at the event itself... it's almost last. This is more or less what lightening talks & successful project presentations provide - although I realise that framing is a bit one dimensional. The thing people want for projects is mentorship and advice.

At that point is where I ran out of time to dwell on this and started to write up where I got. Sadly I have no real conclusion or outcome from all this, except to feedback on the thought process itself. I'd love to know what you think about trying to shift our investment in providing project information to project mentorship / advice. 

Joe

P.s The good news from the feedback is the place we're moving OpenCon is also the place that people say it's most useful.

<img width="578" alt="screenshot 2017-08-09 10 33 50" src="https://user-images.githubusercontent.com/4953703/29208871-bbd5b690-7e83-11e7-8965-10053b093252.png">

_Then, we had a brief follow up chat_

Nick suggested we switch to an interactive, workshop type format with successful project leads hosting that focuses on providing mentorship/advice. So, I thought I'd take a look at feedback/responses to those sessions. The closest analogy to these were the "how-to" workshops we've done in years past. In 2016, the workshops aren't rated much more highly than the project presentations. In 2015, sadly we don't have any data that could help us tell! From this, I think it's basically a toss up as to if this is a better route forwards. 

While continuing to look at this though, another point jumped out at me. Most of our top rated keynotes over the years:
* Erin 2014
* Erin / Mike 2015
have been talks giving mentorship & advice on being open. Usually, these talks focus on _people_, not projects. Those talks have _a lot_ of daylight between them and others usually.

I didn't really see this coming when I started to consider this... but I now think that this might be an excellent use of a carefully chosen (and not necessarily early career) keynote. I'd suggest that the keynote is designed primarily to:
* Provide advice / mentorship.
* Speak to career advancement.
* focus on people, not projects.

The advantage of a keynote here would also be to offset concerns about fragmenting OpenCon too much, having it be too interactive (for introverted folks) and us straying too far from people's day to day challenges. That would leave us with a lot of our goals named above unfilled potentially, but I think there is a lot of room to address that in #4.  

Any feedback from @sparcopen/staff-opencon or @sparcopen/oc-opencon would be especially helpful here. (Note: @sparcopen/oc-opencon you have access to all the year's feedback in the minutes documents)

**Comment by pennybphd** [comment]
Can we do a successful projects zine as swag, which also doubles as a slide
show between talks at the event, and focuses on the people and their big
takeaways/tips with project title and link? Heroes of OpenCon aren't just
the person who gets the orange cape...

**Comment by JosephMcArthur** [comment]
I love that idea, reminds me of the [Mozilla Communities Yearbook](https://docs.google.com/presentation/d/1mBZRneCblkhFvbBKlO29Z8XLeGFRhyR7oQzCMvY2MpA/edit?usp=drive_web) which is an idea we were pretty fond of for a while but never managed to do!

**Comment by npscience** [comment]
+1 for yearbook/zine idea <3

Actual printed booklet seems like a lot of overhead (but nice to keep for posterity). The Mozilla one would be a great way to crowdsource and share info with links. Could this be started before OpenCon, and completed during and shortly after (to help those less confident about putting their own projects in upfront), to aim for a end of (Western) year release by email? May be a nice way to keep people engaged, and ensure we include newer advocates in it too.

**Comment by char-siuu-bao** [comment]
I *love* the zine idea! It would be pretty low cost too (probably between $3-$5 per booklet) in terms of printing costs.  Time and resources in putting the document together, would be the bigger bottleneck, I think!  I think this could also look like a digital gallery highlighting successful projects; It could be a good way to highlight projects that aren't in the room but are in the OpenCon community more broadly, as well (and a way to engage people beyond the main meeting).

**Comment by rchampieux** [comment]
YES!!! to the zine idea!  I think it speaks to the spirit of OpenCon and this community on so many levels.  Let's make it happen.

**Comment by rchampieux** [comment]
Also re project mentoring and advice - this might be another area for which we can borrow / draw some inspiration from a Mozilla program, specifically the open leadership mentoring model.  As I understand it individuals working on a project are matched up with a mentor that provides 1:1 advice, encouragement, brainstorming, etc.  The relationships is kicked off at the a face to face event, but most of the real work/value takes place virtually over a twelve week period.  Could this be a model we could remix for the OpenCon community?

**Comment by char-siuu-bao** [comment]
Matching mentors up (and the Mozilla mentoring @rchampieux mentioned) was something that also came up on today's OC call — so definitely something to consider. Does anyone have the link to Mozilla's model? I'm not super familiar, but it's something worth exploring as a way to support folks not in the room at OpenCon too (and our global community more broadly). 

I still think there's value in making sure early career folks and those who don't normally have a lot of visibility get a chance to be on stage / highlight their work.  Although a zine achieves that to some extent (and I still love the idea!) I would like to see new people on stage, etc... and I think the lightning talks / project presentations really achieve that. Just my 2 cents.

**Comment by rchampieux** [comment]
@lorrainechu3n I tried to find the Mozilla program documentation, but no luck.  I can ask Daniela Saderi and Danielle Robinson, as they're both participating.

**Comment by aldirdiri** [comment]
I love the zine idea. It would be also wonderful to highlight some of the non-participants' projects. Though I still feel positive about having some presentations as well. Perhaps reducing the number and changing the panel style may work out (individual presentation rather than a panel) with a special focus on takeaways (so the projects are more of case studies). This would provide the participants with the necessary inspiration along with some valuable tips to start, improve or support.

**Comment by npscience** [comment]
@JosephMcArthur I like your alternative idea of a keynote about working open - but is this advice out there already (i.e. in Mozilla resources)? What would be the value to this audience?

The Zine would be a good medium to share details of the projects (and would be nice to also include links to resources they have found useful for their projects).
I see getting up on stage in front of everyone as an opportunity for discussion and feedback - i.e. I find the Q&A is the most useful part of bringing people together for a conference.
Could we build on that idea? i.e. Have an open discussion between an experienced project lead and some newer project leads - advice sharing, so that everyone can learn? (This connects with your point above about focussing on people not projects, and on providing mentorship/advice.)

@lorrainechu3n @rchampieux do you mean these docs re Moz framework? http://mozillascience.github.io/leadership-training/03.3-leaders.html

**Comment by char-siuu-bao** [comment]
@JosephMcArthur re: "For "Project presentations & Successful Projects Panel", it would be good to know if people think replacing our panel of successful student projects with one keynote from an out of this world rockstar (like Erin or Mike, in previous years) giving advice on doing open would be good."

I want to emphasize the value in the project presentations and successful projects panel is that it allows us to highlight a diversity of voices and types of work — it's nice to put this in a zine, but I think it's really important to have these voices on stage as well. If we _were_ to replace these sessions with a rockstar keynote, I would like to see this keynote be someone who is not a cis man, and ideally a person of colour or someone doing work on Open from outside of Europe or North America, unlike (the majority of) our keynotes from previous years.

**Comment by aldirdiri** [comment]
I totally agree with @lorrainechu3n if we were to replace the panel with a keynote. It would also be better if the presenter is an EC.

**Comment by rchampieux** [comment]
Hi all.  On the whole, the idea of replacing the project presentations with a rock star keynote doesn't resonate with me, and I'm skeptical it will achieve the outcomes/goals noted above, especially in regards to mentorship.  That said, this kind of keynote can be inspiring and facilitate other important takeaways.  If we do go this route, I think @lorrainechu3n suggestions above are spot on.  

I wonder if we can boost the value of the panel and keep the focus on EC presenters by playing with the framing a bit.  For example, instead of focusing on projects, we could celebrate and learn from community members that are really good at different models of / strategies for advancing openness (e.g. grass roots community building, technological solutions, policy work, partnership building, education, etc).  Of course they might tell their stories through examples of the projects they've worked on, but we could craft the panel format/questions to really elicit the panelists personal experiences, local contexts, advice for others, etc.  

@npscience per your note above, that's not the framework I was referencing (I don't think), but I did reach out to Danielle and Daniela and they passed on some info.  I'll add that here shortly.

**Comment by rchampieux** [comment]
@JosephMcArthur @npscience @lorrainechu3n here is the slide deck Mozilla Science uses for its open leaders mentors training:  https://docs.google.com/presentation/d/1VPQ2w5RBHcw4Rx7h--OwttzkkGTC_cwE-da08Hz_E_E/present?slide=id.g1088c5b110_0_183.  Not a whole lot here, but some good ideas to consider.  Also, Danielle Robison said she would be happy to talk about her experience as a mentor in more detail.  Daniela is also happy to talk about her experience as a mentee.  Rock star OpenCon alums 🎸 💟 🐈

**Comment by Bubblbu** [comment]
I agree with @rchampieux comment. I'm skeptical about replacing the panel with a (probably less EC) rock star keynote. But I think that having a rock star from an underrepresented region & who is also EC, as suggested by @lorrainechu3n and @aldirdiri, would be a great way to do so. 

Although I absolutely love the idea of a zine (:raised_hands:), I think that it is hard to replace the special value that an actual panel/presentation on a stage has. Having the opportunity to speak and present in front of the community, imo, can't be compared to "just" having a spot in a doc. In that regard, huge +1 for Robin's suggestion for a special framing. Ideally the successful students/projects panel could aim for the same "function" as the rock star keynote.

Nevertheless, we could obviously have both zine and panel to have more focus & spotlight on EC presenters & awesome projects.

**Comment by JosephMcArthur** [comment]
Thank you, everyone, for all the amazing feedback here. Really really great. 

Here is what I'd suggest moving forwards:
* Let's try and figure out a way to make a Zine happen. I don't have the foggiest where to start with that but have suggested that making one could be a cool reception.  - #104
- [ ] I'd like to see us keep project presentations. However, I'd like to challenge us to use them to facilitate reporting out from unconferences & encourage great documentation around the doathon. In this way, they might become more last minute but serve to promote ideas, discussions, and projects that're actively engaging in the meeting. We could do this partly by selecting people at the last minute. We could also allow slides, and only allowing people to use meeting documentation to present, as suggested in [point 5 here](https://blog.trelliscience.com/six-tips-for-running-a-successful-unconference/). I realised I've done this before, and it works surprisingly well. 
- [ ] We need to continue a discussion of how best to make mentorship, especially long term mentorship, work for OpenCon. I also love the Mozilla work here and have spoken at length with them about it. The problem for us is how to facilitate it happening. 

Now, where we're not quite ready to move forwards I don't think is on what to do with the successful projects panel. I came here to say let's go with a keynote who's a rock star from an underrepresented region & an EC. I was struggling (despite all of your comments) to ignore all the data suggesting that this format is a lot more compelling. But, then I considered that over the course of OpenCon no session has been advocated for by our OC as strongly as this across the years, and I started to wonder if the data was not telling the full story. So, now I'm back to not knowing!

Now I just have an idea to throw into the hat myself. To maintain a panel, but perhaps learn from what works in the keynotes, we should invite successful project leaders to speak to some of the challenges many of us face e.g:
* Imposter syndrome
* Fear of failure and bouncing back
* Balance, burnout, & brownout
* Identifying as an advocate
* How to keep going
* Being discriminated against 

These themes came up naturally at OpenCon quite a lot last year and it was powerful, and I think resonated with a lot of people (certainly me). I'm not suggesting that everyone speaks to everything, or that their projects don't get spoken about too, but that these topics (and ones like them) would be the lenses that we looked at the session through. 

I'm going to keep this issue open for feedback from @sparcopen/staff-opencon & @sparcopen/oc-opencon

**Comment by npscience** [comment]
+1 to lightning talks / open mic for active/new projects based on the doathon doc. I've also experienced this (software sustainability institute workshop) and it helps focus the doathon.

+1000 to a panel of honesty @josephmcarthur - I too find these talks very useful. This community is the juice I need to inspire action, get my act together, confront my own blockers. Isn't that kind of advice and support what community is all about anyway?

**Comment by JosephMcArthur** [comment]
Discussed this issue with @nshockey yesterday. A few takeaways here that allow us to close this:
* the approach outlined above for project presentations is fine for the super workshops. However, in other cases, we should stick to more prepared presentations. 
* We're good to move forwards on a successful EC initiatives panel that tries to speak to what I suggested in https://github.com/sparcopen/opencon/issues/80#issuecomment-327006380. Rather than having it be all talks, we'd like to have a large segment of it as a heavily moderated & planned discussion with a lot of audience input. So, for example, the session may look like:
  * short ( ~3-5 minute ) project talks (x 5)
  * a few opening (and planned) questions from the moderator to warm up discussion & set tone (~20 minutes)
  * opening up questions to the audience  (~20 minutes). Rather than selecting at random, we'd like to try out software that would aggregate & help us chose questions that the most people were interested in. 
  
In the tone of the session, we'd like to make sure that this is still inspirational and speaks well to what is possible out of the meeting, while acknowledging that few things worth doing are easy personally or professionally.

With that, @nshockey and I feel pretty comfortable moving forwards. We feel like this approach balances what the @sparcopen/oc-opencon has said, with what participants are saying, and what the meeting needs. Structurally, we think we've introduced some important elements to make this more useful to people (e.g greater focus on people, not projects. Increased relevance by allowing deeper audience engagement.)

I'm going to close this now, but please don't hesitate to reopen if you've got concerns or more to add.
