### ISSUE TITLE
Agenda for August 16th Call

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#81]
Some obvious points below:

* Updates:
  * Fundraising
  * Application Process Update
* Program

**Comment by JosephMcArthur** [comment]
* Ask folks to do 10 reviews before the call
* Speak about how many no's before people are removed from the round.

**Comment by char-siuu-bao** [comment]
- Chat about CoC updates, changes and processes (will create a doc to circulate)

**Comment by nshockey** [comment]
Draft agenda for August 16th

- Updates
- Review process
- Code of Conduct changes
- Program
- Any other business

**Comment by JosephMcArthur** [comment]
I expect that the discussion of CoC will take most of the call (or at least it certainly could), but @nshockey is there anything you'd specifically like me to prep for the program discussion? Right now I'd be very happy with a plug for folks to read, consider, and feedback within 1.5 weeks before we generate true "plans" for their approval (most of the issues discuss what I think would be helpful feedback). I'm going to try and get similar posts up for #39 and #4 before the call.

**Comment by char-siuu-bao** [comment]
Just wanted to drop questions we'll be discussing as a group about the COC and that would be great to get feedback on tomorrow:
- Go through new suggested internal process — anything people don't agree with? 
- Discuss what sanctions / repercussions look like (what is appropriate and realistic?)
- Feedback on Code of Conduct Language / section updates on site. 
- Has anyone seen anonymous reporting done at other conferences? How did this work? 
- How do we create a safer space at OpenCon - not just the illusion of a safe space (e.g. should we not have an Open bar at the social this year?) 
- Do we want a designated group to deal with this, and how do we decide this? 
- Any other things that we haven't covered? 

Suggested changes are here (some sections still in progress) https://docs.google.com/document/d/1LkywkSHDJAFmy4GsrY3W02jDO8l_Ovz2KSk9Ek68WQ4/edit#

**Comment by txtbks** [comment]
Opened an issue (#89) to discuss OC outreach to attendees prior to the conference (which came up on today's call).
