### ISSUE TITLE
Research & update CoC / get feedback from OC + staff.

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#83]
- Research other conference COC's and relevant blog posts
- Suggest changes to CoC and compile into Google Doc
- Prepare prompt questions/proposed changes to discuss on OC call on Wednesday

**Comment by char-siuu-bao** [comment]
Useful resources: 

Safe conferences are deliberately designed: https://medium.com/@jmspool/safe-conferences-are-deliberately-designed-2849b6cd3658

Handling harassment incidents swiftly and safely: https://adainitiative.org/2014/07/23/handling-harassment-incidents-swiftly-and-safely/

Harassment report at your conference: what do you do? https://adainitiative.org/2012/10/04/harassment-report-at-your-conference-what-do-you-do/

**Comment by char-siuu-bao** [comment]
Notes being dropped down here: https://docs.google.com/document/d/1LkywkSHDJAFmy4GsrY3W02jDO8l_Ovz2KSk9Ek68WQ4/edit#heading=h.g35vv2irnuf

**Comment by char-siuu-bao** [comment]
Questions for OC: Going through for OC call: 
- Go through internal process — anything people don't agree with? 
- Discuss what sanctions / repercussions look like (what is appropriate and realistic?)
- Feedback on Code of Conduct Language / section updates on site. 
- Has anyone seen anonymous reporting done at other conferences? How did this work? 
- How do we create a safer space at OpenCon - not just the illusion of a safe space (e.g. should we not have an Open bar at the social this year?) 
- Do we want a designated group to deal with this, and how do we decide this? 
- Any other things that we haven't covered?

**Comment by JosephMcArthur** [comment]
leaving a little todo here:

- [x] once we update the CoC it'll need to be updated on Github, as well as the website.

**Comment by char-siuu-bao** [comment]
Note: Public CoC has been updated here - http://www.opencon2017.org/code_of_conduct

Google doc & discussions that preceded the update are here: https://docs.google.com/document/d/1LkywkSHDJAFmy4GsrY3W02jDO8l_Ovz2KSk9Ek68WQ4/edit#
