### ISSUE TITLE
How to make OpenCon more inclusive for English as a second language speakers?

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#84]
- Closed captioning 
- Translators before/after/during event.

**Comment by rchampieux** [comment]
@lorrainechu3n I realize the impact of this strategy is relatively tiny, but for ESL presenters can we encourage them to use their language of preference in presentation materials?

**Comment by JosephMcArthur** [comment]
@lorrainechu3n I'm going to be asking all the speakers on the panels I'm managing comms with to be conscious that folks with ESL will be present - and to talk much slow than usual.

Might be good to say the same to DEI. Just a small step in the right direction here. =

**Comment by JosephMcArthur** [comment]
Using youtube we get auto-captioned video. 

Not much more we can do now, so closing to keep final to-dos clear.
