### ISSUE TITLE
Make sure conference registration has questions around accessibility needs!

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#85]
- Need to chat with Nicole about this when registration from is designed.

**Comment by txtbks** [comment]
Noting that this is in process! We've set up the form in this way: (1) list all of the accommodations that we provide, (2) provide a checklist of accommodations people can request, (3) provide a comment box for people to specify anything else. We also allow people the option to request a phone/skype call to discuss accommodations.

**Comment by char-siuu-bao** [comment]
Just looked over the form, @txtbks, and it looks great! Closing this issue.
