### ISSUE TITLE
Venue accessibility check / Look into Inclusive Room requirements (e.g. gender neutral washrooms)

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#87]
**VENUE ACCESSIBILITY - have someone on site do a walk through and check for these features:** 
- [ ] checklist downloadable here: https://www.americanbar.org/content/dam/aba/administrative/mental_physical_disability/Accessible_Meetings_Toolkit.authcheckdam.pdf

**Create plan to convert rooms to these ones (make sure this is possible)** 
- [ ] Venue has gender neutral bathrooms or is open to designating specific bathrooms as gender neutral
- [ ]  Venue A/V has sound system with microphone & speakers set-up (ideally, wireless microphones)
- [ ] Set up maternity room at venue
- [ ] Set up prayer room at venue
- [ ] Set up quiet room at venue

**Comment by JosephMcArthur** [comment]
In my initial site visit I covered a lot of this: https://docs.google.com/document/d/17ISTZcXBVmO4JvO5_I9AUuwnkOhKalcCQBimNqt7o7c/edit?usp=drive_web from our checklist (haven't looked at the one above). 

A few key points:

* The venue doesn't have gender neutral bathrooms, but was happy with us setting this up. 
* It's got good AV
* I recommended we use onsite hotel rooms for maternity/prayer/quiet/staff rooms, as our other bookable rooms are needed most of the time for breakout spaces. These rooms are just one floor above the venue.

cc @nshockey

**Comment by JosephMcArthur** [comment]
In progress of confirming all this with the venue (having already asked everything on the initial site site), will raise further issues as they arise. 

Closing for now, @lorrainechu3n reopen if there is more you'd like to add / discuss.
