### ISSUE TITLE
Application Notifications

### ISSUE THREAD

**Issue by txtbks** [sparcopen/opencon#88]
Figured it would be useful to have the application notifications under a separate issue. The input for this process will be a list of all applicants marked with a decision from #27, which will be ready the week of Sept 4.

- [ ] Write decision email text
  - [x] Draft
  - [ ] Final
- [ ] Create forms
  - [x] Registration
  - [ ] Waitlist
- [ ] Generate custom fields for input in decision emails
  - [ ] Links to pre-filled forms (or id number + reg code)
  - [ ] Scholarship details (list of expenses that will be covered) 
- [ ] Verify email addresses
  - [ ] Ensure app email is listed as primary email in NB
  - [ ] Pull out people listed as unsubscribed in NB to send separately
- [ ] Upload everything
- [ ] Send!

**Comment by char-siuu-bao** [comment]
@txtbks - thanks for flagging this during today's call. Will work on drafting a google doc with all the emails this week!  

Could we make sure that this year's registration form has a question around accessibility needs (if it doesn't already?) This is something we recommended doing in our DEI report, so I want to make sure we do it in our own registration form!

**Comment by txtbks** [comment]
Thanks @lorrainechu3n! 

Last year the registration form included a box for people to specify their accessibility needs, but I remember one of the pieces of feedback was to be clearer about what is provided up front so it doesn't put as much pressure on people to ask for things. I was thinking of adding a section on accessibility with 1. text describing what accommodations we will definitely have, 2. a checkbox question where we list the facilities we can optionally provide if people request it (maternity room, fragrance free zone, etc.) and 3. a comment box for anything else. Thoughts?

**Comment by char-siuu-bao** [comment]
@txtbks That sounds great!  Do you mind sharing the copy we're using for that before it goes out?
 In our report, we also suggest to "Offer the option of discussing accessibility needs over the phone; this can minimize forming assumptions about the needs of the participant." - I'm not sure if that's something we'd like to do here as well.

A doc based off last year's email notifications copy can be found here: https://docs.google.com/document/d/1zsayv4scvwYFAhF0AVwtUUiEOkM4eBmdCe1RjgoqEec/edit#

Would be great for those with more info about venue details, etc... to fill in some of the missing gaps (cc: @JosephMcArthur, @nshockey) 

Last year, we sent out links to our intro pre-conference webcasts in this initial email. Since we were planning on re-vamping some of our intro webcasts to make them more inclusive, it would be great for us to get the ball rolling on that as well! Joe's opened an issue about this here: https://github.com/sparcopen/opencon/issues/96

**Comment by char-siuu-bao** [comment]
Just had another thought - did we want to send invitation and rejection emails out from different email addresses? (e.g. opencon@sparcopen.org for rejections and a staff email for invitations?) I imagine we don't want replies to acceptances lost in the helpdesk amongst the flurry of other responses and auto-replies we'll be receiving.

**Comment by JosephMcArthur** [comment]
I think sending from opencon@sparcopen.org is fine, Zendesk filters most auto-responses out and then you're left with pretty obvious messages to filter (especially as the subject is different). Around this time is often when we have to go back & forth about funding with people too which is where I think Zendesk will actually excel. 

@txtbks / @lorrainechu3n it would be great to get any updates on this ticket before our staff call either here or on the call. 

I'm going to take a look at the emails now.

Even if we're not ready to make final decisions on R2 applicants, can we get rejections to R0 & R1 apps out this week? We have a lot of people asking and this would deal with 95% of people.

**Comment by char-siuu-bao** [comment]
OK so just reviewing things that I need by Wednesday: 

Application Communications NEED from Nicole:

from @txtbks: 
- Custom text: 
    - List of costs covered by OpenCon 
    - General acceptance blurb #2
- Custom links:
    - Registration link
    - Waitlist confirmation link

from @txtbks / @nshockey
- DATES: I've put September 22nd as the registration deadline, but should some dates be different for those on the waitlist, or those who have been declined scholarship funding? E.g. we should give people more than 1 week to figure out if they can fundraise for the meeting? (This has been noted in the doc as well) 
- DATES: Also need date for notifying people of their waitlist status 
- Link to new page for paying $300 fee this year. 

from @JosephMcArthur:
- any updated copy about the do-a-thon you want to include for this year / communicate to people
