### ISSUE TITLE
Pre-conference outreach from the OC to attendees

### ISSUE THREAD

**Issue by txtbks** [sparcopen/opencon#89]
On the 8/16 OC call we discussed ways to help attendees -- especially new ones -- feel prepared and welcome, and provide an additional venue for people to ask questions. The two ideas we discussed were: 

- Personal emails from OC members to attendees (did this last year)
- Office hours staffed by OC members

The emails went well last year. About two weeks out we had the OC split up the attendee list and send an email to each person welcoming them and starting a discussion about their interests/questions. Perhaps this year we could consider starting this earlier, to provide time for more conversation to take place. 

Office hours would be new this year, but could be a nice way to make people feel welcome. Based on the application review process, office hours may or may not be well attended :) but we always hear positive feedback that it's helpful to have the option, regardless of how many people take advantage of it.

Any other ideas? What do people think of these?

**Comment by JosephMcArthur** [comment]
Personal emails from OC members to attendees are in progress. Closing this for now unless we think we have time to put together office hours, since it's not been mentioned yet I'm assuming not.
