### ISSUE TITLE
Agenda for June 14th OC call

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#9]
@nshockey / @txtbks assigning you both to hash this out :) 

So far:
* Updates since last OC call
* Finalize text for application form and review forms
* Application review process and software design
* Promoting the application process
* OC sub-groups
* For future consideration: considering key themes for 2017 program

**Comment by nshockey** [comment]
Split the discussion around applications into a few discrete items. @txtbks please refine as you see fit. Also added key themes for 2017 program for the OC to begin thinking about before our third call.

**Comment by txtbks** [comment]
Thanks @nshockey, looks good to me. I made a few tweaks, but agree splitting it up that way makes sense.

**Comment by JosephMcArthur** [comment]
@nshockey has the time been confirmed? I only have a hold on my calendar for a couple of hours.

**Comment by rchampieux** [comment]
@nshockey and team, do we have a time and access details for the OC call on Wednesday?  Back from Chile and getting caught up 😸
